name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            whoami
            pwd
            ls /home
            export PATH=$PATH:/usr/bin

            cd /home/ubuntu/Took-Tak-back

            git pull origin main

            /usr/bin/npm install

            /usr/bin/pm2 restart tooktak-backend
