name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
  export PATH=$PATH:/usr/local/bin:/usr/bin
  cd /home/ubuntu/Took-Tak-back/Took-Tak
  git pull origin main
  npm install
  pm2 restart tooktak-backend
